grid_search:
  class: GridSearchCV
  module: sklearn.model_selection
  params:
    cv: 4
    verbose: 3
    refit: roc_auc_ovr_weighted
    scoring: [f1_weighted, roc_auc_ovr_weighted, balanced_accuracy]

model_selection:
  module_1:
    class: RandomForestClassifier
    module: sklearn.ensemble
    params:
      random_state: 2023
    search_param_grid:
      min_samples_leaf: [1, 3, 5]
      n_estimators: [100,300,400,500]
      criterion: ['gini','log_loss']
      max_depth: [4,8,12,16,20,None]
      class_weight: [balanced, balanced_subsample]

  module_2:
    class: KNeighborsClassifier
    module: sklearn.neighbors
    params:
      algorithm: auto
      weights: distance
    search_param_grid: 
      n_neighbors: [3,5,9,11,13,15,20,24]
      

